2022/09/01 15:29:23 [error] 23#23: *2 open() "/var/www/html/robots.txt" failed (2: No such file or directory), client: 172.27.0.1, server: localhost, request: "GET /robots.txt?1662046163835 HTTP/1.1", host: "localhost:8080"
2022/09/01 15:29:25 [error] 25#25: *5 open() "/var/www/html/robots.txt" failed (2: No such file or directory), client: 172.27.0.1, server: localhost, request: "GET /robots.txt?1662046165590 HTTP/1.1", host: "localhost:8080"
2022/09/01 15:29:25 [error] 24#24: *3 open() "/var/www/html/favicon.ico" failed (2: No such file or directory), client: 172.27.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2022/09/01 15:46:33 [error] 22#22: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Log Files] File '/var/www/logs/xdebug.log' could not be opened.PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.29.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.29.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.3:9000", host: "localhost:8080"
2022/09/01 15:46:33 [error] 23#23: *3 open() "/var/www/html/robots.txt" failed (2: No such file or directory), client: 172.29.0.1, server: localhost, request: "GET /robots.txt?1662047193519 HTTP/1.1", host: "localhost:8080"
2022/09/01 15:46:34 [error] 22#22: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Log Files] File '/var/www/logs/xdebug.log' could not be opened.PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.29.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.29.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.3:9000", host: "localhost:8080"
2022/09/01 15:46:34 [error] 23#23: *3 open() "/var/www/html/robots.txt" failed (2: No such file or directory), client: 172.29.0.1, server: localhost, request: "GET /robots.txt?1662047194392 HTTP/1.1", host: "localhost:8080"
2022/09/01 15:46:41 [error] 24#24: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Log Files] File '/var/www/logs/xdebug.log' could not be opened.PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.29.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.29.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.3:9000", host: "localhost:8080"
2022/09/01 15:46:41 [error] 25#25: *7 open() "/var/www/html/robots.txt" failed (2: No such file or directory), client: 172.29.0.1, server: localhost, request: "GET /robots.txt?1662047201649 HTTP/1.1", host: "localhost:8080"
2022/09/01 15:46:41 [error] 24#24: *5 open() "/var/www/html/favicon.ico" failed (2: No such file or directory), client: 172.29.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2022/09/01 15:50:55 [error] 24#24: *5 open() "/var/www/html/robots.txt" failed (2: No such file or directory), client: 192.168.16.1, server: localhost, request: "GET /robots.txt?1662047455879 HTTP/1.1", host: "localhost:8080"
2022/09/01 15:50:55 [error] 23#23: *3 open() "/var/www/html/favicon.ico" failed (2: No such file or directory), client: 192.168.16.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
